#let clothing = (
  (n: "Alltagskleidung", rs: 0, zonen: "Torso, Arme, Beine", w: "1 kg", malus: 0, cost: 2, d: "Reguläres Textilgewebe. Bietet keinen kinetischen Widerstand. Ignoriert einwirkende Kräfte."),
  (n: "Arbeitskleidung", rs: 1, zonen: "Torso, Arme, Beine", w: "2 kg", malus: 0, cost: 5, d: "Verstärktes Tuch. Dämpft rudimentäre Abschürfungen. Erzwingt minimalen Schutz."),
  (n: "Brustpanzer", rs: 4, zonen: "Torso", w: "15 kg", malus: -1, cost: 150, d: "Massive Stahlplatte. Schützt vitale Organe. Erzwingt das Abprallen von Nahkampfangriffen."),
  (n: "Festgewand", rs: 0, zonen: "Torso, Arme, Beine", w: "1,5 kg", malus: 0, cost: 50, d: "Hochwertige Textilien. Sichern die gesellschaftliche Repräsentation. Entbehren jeglicher Panzerung."),
  (n: "Gehärtete Lederrüstung", rs: 2, zonen: "Torso, Arme, Beine", w: "5 kg", malus: 0, cost: 40, d: "Gekochtes und geformtes Leder. Absorbiert signifikante kinetische Energie. Behält moderate Flexibilität."),
  (n: "Geschlossener Helm", rs: 5, zonen: "Kopf", w: "2,5 kg", malus: 0, cost: 80, d: "Massiver Stahlhelm mit Gesichtsschutz. Blockiert frontale Angriffe. Schränkt das Sichtfeld ein."),
  (n: "Halbe Plattenrüstung", rs: 5, zonen: "Torso, Arme, Beine", w: "12 kg", malus: -1, cost: 250, d: "Kombination aus Kette und Platte. Manifestiert hohe Integrität. Reduziert die Mobilität."),
  (n: "Kettenhandschuhe", rs: 3, zonen: "Hände", w: "1 kg", malus: 0, cost: 25, d: "Stahlgeflecht. Sichern die Handknochen gegen Klingen. Schränken die Feinmotorik ein."),
  (n: "Kettenhaube", rs: 3, zonen: "Kopf", w: "2 kg", malus: 0, cost: 35, d: "Geflecht aus Stahlringen. Schützt Schädel und Nacken vor Schnittwunden."),
  (n: "Kettenhemd", rs: 3, zonen: "Torso, Arme", w: "10 kg", malus: -1, cost: 100, d: "Dichtes Stahlgeflecht. Stoppt eindringende Waffen. Verteilt punktuelle Wucht auf größere Flächen."),
  (n: "Lederhandschuhe", rs: 1, zonen: "Hände", w: "0,5 kg", malus: 0, cost: 5, d: "Dickes Leder. Schützt vor Hitze und scharfen Kanten. Reduziert das Risiko manueller Verletzungen."),
  (n: "Lederhelm", rs: 1, zonen: "Kopf", w: "0,5 kg", malus: 0, cost: 10, d: "Kopfbedeckung aus festem Leder. Schirmt das kognitive Zentrum vor leichten Schlägen ab."),
  (n: "Lederhose", rs: 1, zonen: "Beine", w: "1 kg", malus: 0, cost: 15, d: "Robustes Beinkleid. Verhindert leichte Schnittwunden. Garantiert hohe Agilität."),
  (n: "Lederjacke", rs: 1, zonen: "Torso, Arme", w: "1,5 kg", malus: 0, cost: 20, d: "Dichtes Leder. Absorbiert geringe kinetische Energie. Diktieren grundlegende Überlebensfähigkeit."),
  (n: "Ledermantel", rs: 1, zonen: "Torso, Arme, Beine", w: "2,5 kg", malus: 0, cost: 30, d: "Schwerer Ledermantel. Erweitert die Protektion. Manifestiert eine solide Barriere gegen Witterung und leichte Angriffe."),
  (n: "Lederschuhe", rs: 0, zonen: "Füße", w: "1 kg", malus: 0, cost: 5, d: "Einfaches Schuhwerk. Isolieren gegen Bodentemperatur. Bieten keinen strukturellen Schutz."),
  (n: "Nietenleder", rs: 2, zonen: "Torso, Arme, Beine", w: "6 kg", malus: 0, cost: 50, d: "Mit Metallstiften verstärktes Leder. Erhöht den Widerstand gegen Hiebwaffen. Diktieren verbesserte Protektion."),
  (n: "Plattenhandschuhe", rs: 4, zonen: "Hände", w: "1,5 kg", malus: 0, cost: 40, d: "Gelenkige Stahlplatten. Schirmen die Extremitäten vollständig ab. Erhöhen die Wucht waffenloser Schläge."),
  (n: "Plattenstiefel", rs: 4, zonen: "Füße", w: "2 kg", malus: -1, cost: 60, d: "Stahlverkleidetes Schuhwerk. Ignorieren massive Gewalteinwirkung auf die Füße. Erschweren lautlose Fortbewegung."),
  (n: "Ringpanzer", rs: 3, zonen: "Torso, Arme, Beine", w: "8 kg", malus: -1, cost: 80, d: "Auf Leder genähte Metallringe. Fangen Klingen ab. Schränken die Agilität geringfügig ein."),
  (n: "Schuppenpanzer", rs: 4, zonen: "Torso, Arme, Beine", w: "14 kg", malus: -1, cost: 120, d: "Überlappende Metallplättchen. Blockieren Projektile und Hiebe. Erzwingen signifikanten Schutz."),
  (n: "Schwere Stiefel", rs: 1, zonen: "Füße", w: "1,5 kg", malus: 0, cost: 10, d: "Dickes Lederprofil. Sichert den Stand. Verhindert minimale Traumata."),
  (n: "Stahlhelm", rs: 4, zonen: "Kopf", w: "2 kg", malus: 0, cost: 40, d: "Gehärteter Stahlguss. Absorbiert letale Krafteinwirkungen. Sichert das kognitive Zentrum."),
  (n: "Stahlkappenstiefel", rs: 2, zonen: "Füße", w: "2 kg", malus: 0, cost: 25, d: "Verstärktes Schuhwerk. Sichert die Basis-Extremitäten. Verhindert strukturelles Versagen der Zehenknochen."),
  (n: "Stoffhandschuhe", rs: 0, zonen: "Hände", w: "0,1 kg", malus: 0, cost: 2, d: "Einfacher Stoff. Verhindern Verschmutzung. Bieten keinen kinetischen Schutz."),
  (n: "Vollplatte", rs: 6, zonen: "Torso, Arme, Beine", w: "25 kg", malus: -2, cost: 500, d: "Vollständige Stahlpanzerung. Umschließt den gesamten Körper. Manifestiert maximale Integrität im offenen Konflikt. Reduziert den Bewegungsradius maßgeblich."),
  (n: "Winterbekleidung", rs: 0, zonen: "Torso, Arme, Beine", w: "3 kg", malus: 0, cost: 15, d: "Isolierendes Gewebe. Verhindert thermischen Verlust. Bietet keinen Schutz vor Waffengewalt.")
)