// #let traits = (
//   pos: (
//     (n: "Anpassungsfähig", desc: "Kann sich gut an neue Situationen und Umstände anpassen.", s: (1, 2, 3), k: 1, a: ("Resistent", "Starr", "Stur", "Trotzig")),
//     (n: "Aufrichtig", desc: "Ehrlich und aufrichtig in seinen Worten und Taten.", s: (1, 2, 3), k: 1, a: ("Lügen", "Zynisch")),
//     (n: "Ehrgeizig", desc: "Strebt nach Erfolg und Anerkennung.", s: (1, 2, 3), k: 1, a: ("Faul", "Passiv")),
//     (n: "Eigenständig", desc: "Unabhängig und selbstbestimmt.", s: (1, 2, 3), k: 1, a: none),
//     (n: "Einfühlsam", desc: "Kann die Gefühle anderer verstehen und nachvollziehen.", s: (1, 2, 3), k: 1, a: ("Arrogant", "Kalt", "Rücksichtslos", "Unsensibel", "Verurteilend")),
//     (n: "Fantasievoll", desc: "Besitzt eine reiche Fantasie und Kreativität.", s: (1, 2, 3), k: 1, a: ("Einfältig", "Starr")),
//     (n: "Freundlich", desc: "Hilfsbereit und freundlich im Umgang mit anderen.", s: (1, 2, 3), k: 1, a: ("Arrogant", "Jähzornig", "Kalt")),
//     (n: "Generös", desc: "Großzügig und freigiebig.", s: (1, 2, 3), k: 1, a: ("Geizig", "Selbstsüchtig")),
//     (n: "Gründlich", desc: "Arbeitet sorgfältig und genau.", s: (1, 2, 3), k: 1, a: ("Inkonsequent", "Unordentlich")),
//     (n: "Hilfsbereit", desc: "Steht anderen gerne mit Rat und Tat zur Seite.", s: (1, 2, 3), k: 1, a: ("Rücksichtslos", "Selbstsüchtig")),
//     (n: "Humorvoll", desc: "Besitzt einen guten Sinn für Humor.", s: (1, 2, 3), k: 1, a: ("Bitter", "Zynisch")),
//     (n: "Kreativ", desc: "Erfindet und gestaltet neue Dinge.", s: (1, 2, 3), k: 1, a: ("Starr",)),
//     (n: "Lebensfroh", desc: "Hat eine positive Lebenseinstellung.", s: (1, 2, 3), k: 1, a: ("Bitter", "Enttäuscht", "Negativ", "Verzweifelt")),
//     (n: "Leidenschaftlich", desc: "Engagiert und mit Begeisterung bei der Sache.", s: (1, 2, 3), k: 1, a: ("Kalt", "Passiv")),
//     (n: "Loyal", desc: "Steht zu seinen Freunden und Überzeugungen.", s: (1, 2, 3), k: 1, a: ("Unzuverlässig", "Wankelmütig")),
//     (n: "Nachdenklich", desc: "Denkt viel nach und reflektiert.", s: (1, 2, 3), k: 1, a: ("Einfältig", "Impulsiv")),
//     (n: "Optimistisch", desc: "Sieht die positiven Seiten der Dinge.", s: (1, 2, 3), k: 1, a: ("Enttäuscht", "Negativ", "Verzweifelt", "Zynisch")),
//     (n: "Resilient", desc: "Kann mit Rückschlägen gut umgehen.", s: (1, 2, 3), k: 1, a: ("Verzweifelt",)),
//     (n: "Ruhig", desc: "Ausgeglichen und gelassen.", s: (1, 2, 3), k: 1, a: ("Impulsiv", "Jähzornig", "Nervös", "Wütend")),
//     (n: "Selbstbewusst", desc: "Hat Vertrauen in sich selbst.", s: (1, 2, 3), k: 1, a: ("Nervös", "Schüchtern")),
//     // (n: "Unabhängig", desc: "Unabhängig und selbstbestimmt.", s: (1, 2, 3), k: 1, a: none),
//     (n: "Verantwortungsbewusst", desc: "Übernimmt Verantwortung für seine Handlungen.", s: (1, 2, 3), k: 1, a: ("Faul", "Inkonsequent", "Unzuverlässig")),
//     (n: "Visionär", desc: "Hat Visionen und Zukunftspläne.", s: (1, 2, 3), k: 1, a: ("Einfältig", "Starr")),
//     (n: "Wissbegierig", desc: "Hat ein großes Interesse an Wissen und Lernen.", s: (1, 2, 3), k: 1, a: ("Einfältig", "Passiv")),
//     (n: "Zielstrebig", desc: "Verfolgt seine Ziele mit Entschlossenheit.", s: (1, 2, 3), k: 1, a: ("Faul", "Passiv", "Verträumt", "Wankelmütig"))
//   ),
//   neg: (
//     (n: "Arrogant", desc: "Arrogant ist eine überhebliche Haltung anderen Gegenüber.", s: (1, 2, 3), e: 1, a: ("Einfühlsam", "Freundlich")),
//     (n: "Bitter", desc: "Von Groll und Verbitterung geprägt, oft aufgrund vergangener Enttäuschungen.", s: (1, 2, 3), e: 1, a: ("Humorvoll", "Lebensfroh")),
//     (n: "Eifersüchtig", desc: "Von Neid und Missgunst gegenüber anderen, insbesondere deren Besitz oder Erfolg, bestimmt.", s: (1, 2, 3), e: 1, a: none),
//     (n: "Einfältig", desc: "Naiv und leichtgläubig, mangelnde Intelligenz oder Urteilsfähigkeit zeigend.", s: (1, 2, 3), e: 1, a: ("Fantasievoll", "Nachdenklich", "Visionär", "Wissbegierig")),
//     (n: "Enttäuscht", desc: "Von jemandem oder etwas enttäuscht, mit Verlust von Hoffnung oder Vertrauen verbunden.", s: (1, 2, 3), e: 1, a: ("Lebensfroh", "Optimistisch")),
//     (n: "Faul", desc: "Arbeitsscheu und wenig bemüht, Aufgaben zu erledigen.", s: (1, 2, 3), e: 1, a: ("Ehrgeizig", "Verantwortungsbewusst", "Zielstrebig")),
//     (n: "Geizig", desc: "Ungern Geld ausgebend, sparsam bis zum Extrem.", s: (1, 2, 3), e: 1, a: ("Generös",)),
//     (n: "Impulsiv", desc: "Handelt spontan und ohne nachzudenken, oft mit unvorhergesehenen Konsequenzen.", s: (1, 2, 3), e: 1, a: ("Nachdenklich", "Ruhig")),
//     (n: "Inkonsequent", desc: "Verhält sich unbeständig und widersprüchlich, hält Versprechen nicht ein.", s: (1, 2, 3), e: 1, a: ("Gründlich", "Loyal", "Verantwortungsbewusst")),
//     (n: "Introvertiert", desc: "Zurückhaltend und eher in sich gekehrt, bevorzugt die Einsamkeit.", s: (1, 2, 3), e: 1, a: none),
//     (n: "Jähzornig", desc: "Neigt zu plötzlichen und heftigen Wutausbrüchen.", s: (1, 2, 3), e: 1, a: ("Freundlich", "Ruhig")),
//     (n: "Kalt", desc: "Emotional distanziert und unnahbar, zeigt wenig Empathie.", s: (1, 2, 3), e: 1, a: ("Einfühlsam", "Freundlich", "Leidenschaftlich")),
//     (n: "Kritisch", desc: "Beurteilt Dinge und Menschen genau und oft negativ.", s: (1, 2, 3), e: 1, a: none),
//     (n: "Lügen", desc: "Sagt absichtlich Unwahrheiten.", s: (1, 2, 3), e: 1, a: ("Aufrichtig",)),
//     (n: "Nachtragend", desc: "Kann verzeihen nur schwer, vergisst alte Konflikte nicht.", s: (1, 2, 3), e: 1, a: none),
//     (n: "Negativ", desc: "Sieht in allem stets das Schlechte und erwartet das Schlimmste.", s: (1, 2, 3), e: 1, a: ("Lebensfroh", "Optimistisch")),
//     (n: "Nervös", desc: "Ist leicht aus der Ruhe zu bringen und oft angespannt.", s: (1, 2, 3), e: 1, a: ("Ruhig", "Selbstbewusst")),
//     (n: "Passiv", desc: "Ergreift selten die Initiative und lässt Dinge geschehen.", s: (1, 2, 3), e: 1, a: ("Ehrgeizig", "Leidenschaftlich", "Wissbegierig", "Zielstrebig")),
//     (n: "Resistent", desc: "Wehrt sich innerlich gegen Veränderungen und Einflüsse.", s: (1, 2, 3), e: 1, a: ("Anpassungsfähig",)),
//     (n: "Rücksichtslos", desc: "Handelt ohne Rücksicht auf die Gefühle oder das Wohlergehen anderer.", s: (1, 2, 3), e: 1, a: ("Einfühlsam", "Hilfsbereit")),
//     (n: "Sarkastisch", desc: "Reagiert oft mit beißendem Spott und beißender Ironie.", s: (1, 2, 3), e: 1, a: ("Aufrichtig",)),
//     (n: "Schüchtern", desc: "Ist in Gesellschaft zurückhaltend und furchtsam.", s: (1, 2, 3), e: 1, a: ("Selbstbewusst",)),
//     (n: "Selbstsüchtig", desc: "Denkt nur an sich selbst und seine eigenen Bedürfnisse.", s: (1, 2, 3), e: 1, a: ("Generös", "Hilfsbereit")),
//     (n: "Starr", desc: "Unflexibel und unfähig, seine Meinung zu ändern.", s: (1, 2, 3), e: 1, a: ("Anpassungsfähig", "Fantasievoll", "Kreativ", "Visionär")),
//     (n: "Stur", desc: "Beharrt trotz besseren Wissens auf seiner Meinung.", s: (1, 2, 3), e: 1, a: ("Anpassungsfähig",)),
//     (n: "Trotzig", desc: "Widersetzt sich aus Trotz und Trotzgehabe.", s: (1, 2, 3), e: 1, a: ("Anpassungsfähig",)),
//     (n: "Unordentlich", desc: "Hält seine Umgebung nicht sauber und ordentlich.", s: (1, 2, 3), e: 1, a: ("Gründlich",)),
//     (n: "Unsensibel", desc: "Fehlt an Einfühlungsvermögen und Verständnis für die Gefühle anderer.", s: (1, 2, 3), e: 1, a: ("Einfühlsam",)),
//     (n: "Unzuverlässig", desc: "Kann man sich nicht auf ihn verlassen.", s: (1, 2, 3), e: 1, a: ("Loyal", "Verantwortungsbewusst")),
//     (n: "Verträumt", desc: "Ist oft in Gedanken versunken.", s: (1, 2, 3), e: 1, a: ("Zielstrebig",)),
//     (n: "Verurteilend", desc: "Beurteilt andere Menschen schnell und negativ.", s: (1, 2, 3), e: 1, a: ("Einfühlsam",)),
//     (n: "Verzweifelt", desc: "Von Hoffnungslosigkeit und Verzweiflung geprägt.", s: (1, 2, 3), e: 1, a: ("Lebensfroh", "Optimistisch", "Resilient")),
//     (n: "Wankelmütig", desc: "Ändert oft seine Meinung und Entscheidungen.", s: (1, 2, 3), e: 1, a: ("Loyal", "Zielstrebig")),
//     (n: "Wütend", desc: "Von starkem Ärger und Zorn erfüllt.", s: (1, 2, 3), e: 1, a: ("Ruhig",)),
//     (n: "Zynisch", desc: "Misstrauisch und glaubt nicht an das Gute im Menschen.", s: (1, 2, 3), e: 1, a: ("Aufrichtig", "Humorvoll", "Optimistisch"))
//   )
// )



#let traits = (
  pos: (
    (n: "Anpassungsfähig", desc: "Der Protagonist adaptiert neue Umstände nahtlos.", regel: none, s: (1, 2, 3), k: 1, a: ("Resistent", "Starr", "Stur", "Trotzig")),
    (n: "Aufrichtig", desc: "Der Protagonist artikuliert und handelt wahrheitsgemäß.", regel: "Die Eigenschaft erzwingt einen Bonus auf Vertrauensaufbau. Der Bonus entspricht der Stufe.", s: (1, 2, 3), k: 1, a: ("Lügen", "Zynisch")),
    (n: "Ehrgeizig", desc: "Der Protagonist forciert persönlichen Erfolg.", regel: none, s: (1, 2, 3), k: 1, a: ("Faul", "Passiv")),
    (n: "Eigenständig", desc: "Der Protagonist operiert vollkommen autark.", regel: none, s: (1, 2, 3), k: 1, a: none),
    (n: "Einfühlsam", desc: "Der Protagonist analysiert fremde Emotionen präzise.", regel: none, s: (1, 2, 3), k: 1, a: ("Arrogant", "Kalt", "Rücksichtslos", "Unsensibel", "Verurteilend")),
    (n: "Fantasievoll", desc: "Der Protagonist manifestiert kreative Konzepte.", regel: none, s: (1, 2, 3), k: 1, a: ("Einfältig", "Starr")),
    (n: "Freundlich", desc: "Der Protagonist interagiert kooperativ.", regel: none, s: (1, 2, 3), k: 1, a: ("Arrogant", "Jähzornig", "Kalt")),
    (n: "Generös", desc: "Der Protagonist teilt Ressourcen bedingungslos.", regel: none, s: (1, 2, 3), k: 1, a: ("Geizig", "Selbstsüchtig")),
    (n: "Gründlich", desc: "Der Protagonist exekutiert Aufgaben hochpräzise.", regel: "Die Eigenschaft verhindert das Übersehen von Details. Dies diktiert einen Bonus auf Materialanalyse oder Ressourcenmanagement. Der Bonus entspricht der Stufe.", s: (1, 2, 3), k: 1, a: ("Inkonsequent", "Unordentlich")),
    (n: "Hilfsbereit", desc: "Der Protagonist unterstützt Verbündete aktiv.", regel: none, s: (1, 2, 3), k: 1, a: ("Rücksichtslos", "Selbstsüchtig")),
    (n: "Humorvoll", desc: "Der Protagonist entspannt soziale Situationen.", regel: none, s: (1, 2, 3), k: 1, a: ("Bitter", "Zynisch")),
    (n: "Kreativ", desc: "Der Protagonist konstruiert Innovationen.", regel: none, s: (1, 2, 3), k: 1, a: ("Starr",)),
    (n: "Lebensfroh", desc: "Der Protagonist bewahrt absoluten Optimismus.", regel: none, s: (1, 2, 3), k: 1, a: ("Bitter", "Enttäuscht", "Negativ", "Verzweifelt")),
    (n: "Leidenschaftlich", desc: "Der Protagonist agiert mit maximalem Fokus.", regel: none, s: (1, 2, 3), k: 1, a: ("Kalt", "Passiv")),
    (n: "Loyal", desc: "Der Protagonist verteidigt Verbündete kompromisslos.", regel: "Die Abwehr eines direkten Angriffs auf Gefährten erzwingt einen Bonus auf Mentale Stärke oder Kampffertigkeiten. Der Bonus entspricht der Stufe.", s: (1, 2, 3), k: 1, a: ("Unzuverlässig", "Wankelmütig")),
    (n: "Nachdenklich", desc: "Der Protagonist reflektiert Handlungen systematisch.", regel: "Das ruhige Studieren eines Problems diktiert einen Bonus auf analytische Proben. Der Bonus entspricht der Stufe.", s: (1, 2, 3), k: 1, a: ("Einfältig", "Impulsiv")),
    (n: "Optimistisch", desc: "Der Protagonist fokussiert positive Resultate.", regel: "Die Eigenschaft verhindert das Aufgeben. Dies manifestiert einen Bonus auf Überlebensstrategie in feindlichen Umgebungen. Der Bonus entspricht der Stufe.", s: (1, 2, 3), k: 1, a: ("Enttäuscht", "Negativ", "Verzweifelt", "Zynisch")),
    (n: "Resilient", desc: "Der Protagonist absorbiert Rückschläge.", regel: none, s: (1, 2, 3), k: 1, a: ("Verzweifelt",)),
    (n: "Ruhig", desc: "Der Protagonist agiert vollkommen gelassen.", regel: "Die Eigenschaft manifestiert eine extrem ruhige Hand. Dies erzwingt einen Bonus auf Präzisionsarbeiten oder das Zielen im Fernkampf. Der Bonus entspricht der Stufe.", s: (1, 2, 3), k: 1, a: ("Impulsiv", "Jähzornig", "Nervös", "Wütend")),
    (n: "Selbstbewusst", desc: "Der Protagonist vertraut den eigenen Kapazitäten.", regel: none, s: (1, 2, 3), k: 1, a: ("Nervös", "Schüchtern")),
    (n: "Verantwortungsbewusst", desc: "Der Protagonist übernimmt Konsequenzen.", regel: none, s: (1, 2, 3), k: 1, a: ("Faul", "Inkonsequent", "Unzuverlässig")),
    (n: "Visionär", desc: "Der Protagonist plant zukünftige Entwicklungen.", regel: none, s: (1, 2, 3), k: 1, a: ("Einfältig", "Starr")),
    (n: "Wissbegierig", desc: "Der Protagonist akkumuliert Fakten.", regel: none, s: (1, 2, 3), k: 1, a: ("Einfältig", "Passiv")),
    (n: "Zielstrebig", desc: "Der Protagonist forciert seine Vorhaben.", regel: none, s: (1, 2, 3), k: 1, a: ("Faul", "Passiv", "Verträumt", "Wankelmütig"))
  ),
  neg: (
    (n: "Arrogant", desc: "Der Protagonist deklariert eigene Überlegenheit.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Einfühlsam", "Freundlich")),
    (n: "Bitter", desc: "Der Protagonist konserviert alten Groll.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Humorvoll", "Lebensfroh")),
    (n: "Eifersüchtig", desc: "Der Protagonist neidet fremden Besitz.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: none),
    (n: "Einfältig", desc: "Der Protagonist ignoriert komplexe Zusammenhänge.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Fantasievoll", "Nachdenklich", "Visionär", "Wissbegierig")),
    (n: "Enttäuscht", desc: "Der Protagonist verweigert neues Vertrauen.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Lebensfroh", "Optimistisch")),
    (n: "Faul", desc: "Der Protagonist verweigert physische und mentale Anstrengung.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Ehrgeizig", "Verantwortungsbewusst", "Zielstrebig")),
    (n: "Geizig", desc: "Der Protagonist blockiert die Ressourcenverteilung.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Generös",)),
    (n: "Impulsiv", desc: "Der Protagonist agiert ohne Vorplanung.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Nachdenklich", "Ruhig")),
    (n: "Inkonsequent", desc: "Der Protagonist bricht bestehende Abmachungen.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Gründlich", "Loyal", "Verantwortungsbewusst")),
    (n: "Introvertiert", desc: "Der Protagonist meidet soziale Interaktion.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: none),
    (n: "Jähzornig", desc: "Der Protagonist eskaliert Konflikte unkontrolliert.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Freundlich", "Ruhig")),
    (n: "Kalt", desc: "Der Protagonist ignoriert emotionale Parameter.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Einfühlsam", "Freundlich", "Leidenschaftlich")),
    (n: "Kritisch", desc: "Der Protagonist attackiert fremde Konzepte.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: none),
    (n: "Lügen", desc: "Der Protagonist artikuliert gezielte Unwahrheiten.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Aufrichtig",)),
    (n: "Nachtragend", desc: "Der Protagonist konserviert alte Konflikte.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: none),
    (n: "Negativ", desc: "Der Protagonist fokussiert unvermeidliches Scheitern.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Lebensfroh", "Optimistisch")),
    (n: "Nervös", desc: "Der Protagonist verliert den mentalen Fokus.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Ruhig", "Selbstbewusst")),
    (n: "Passiv", desc: "Der Protagonist verweigert eigene Initiativen.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Ehrgeizig", "Leidenschaftlich", "Wissbegierig", "Zielstrebig")),
    (n: "Resistent", desc: "Der Protagonist blockiert notwendige Veränderungen.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Anpassungsfähig",)),
    (n: "Rücksichtslos", desc: "Der Protagonist ignoriert kollaterale Schäden.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Einfühlsam", "Hilfsbereit")),
    (n: "Sarkastisch", desc: "Der Protagonist kommuniziert durch beißenden Spott.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Aufrichtig",)),
    (n: "Schüchtern", desc: "Der Protagonist meidet zentrale Aufmerksamkeit.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Selbstbewusst",)),
    (n: "Selbstsüchtig", desc: "Der Protagonist priorisiert eigene Bedürfnisse.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Generös", "Hilfsbereit")),
    (n: "Starr", desc: "Der Protagonist verweigert konzeptionelle Anpassungen.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Anpassungsfähig", "Fantasievoll", "Kreativ", "Visionär")),
    (n: "Stur", desc: "Der Protagonist ignoriert rationale Argumente.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Anpassungsfähig",)),
    (n: "Trotzig", desc: "Der Protagonist attackiert etablierte Autorität.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Anpassungsfähig",)),
    (n: "Unordentlich", desc: "Der Protagonist vernachlässigt systematische Strukturen.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Gründlich",)),
    (n: "Unsensibel", desc: "Der Protagonist verletzt fremde Emotionen.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Einfühlsam",)),
    (n: "Unzuverlässig", desc: "Der Protagonist ignoriert getroffene Vereinbarungen.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Loyal", "Verantwortungsbewusst")),
    (n: "Verträumt", desc: "Der Protagonist verliert den Fokus zur Realität.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Zielstrebig",)),
    (n: "Verurteilend", desc: "Der Protagonist deklariert negative Urteile.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Einfühlsam",)),
    (n: "Verzweifelt", desc: "Der Protagonist kapituliert vor Herausforderungen.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Lebensfroh", "Optimistisch", "Resilient")),
    (n: "Wankelmütig", desc: "Der Protagonist revidiert getroffene Entschlüsse.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Loyal", "Zielstrebig")),
    (n: "Wütend", desc: "Der Protagonist fokussiert reine Aggression.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Ruhig",)),
    (n: "Zynisch", desc: "Der Protagonist attackiert idealistische Motive.", regel: "Die Situation aktiviert das Laster. Dies erzwingt einen negativen Modifikator auf betroffene Fertigkeitsproben. Der Malus entspricht der Stufe.", s: (1, 2, 3), e: 1, a: ("Aufrichtig", "Humorvoll", "Optimistisch"))
  )
)